services:
  - type: web
    name: download-app-backend
    env: python
    python_version: 3.9.12  # Explicitly setting a stable Python version
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: "1"
    buildFilter:
      paths:
        - app/**
        - requirements.txt
        - Procfile
    autoDeploy: true